export const FILTER_GROUPS = [
  {
    key: 'platform',
    label: 'Platform',
    options: [
      { value: 'instagram', label: 'Instagram' },
      { value: 'youtube', label: 'YouTube' },
      { value: 'facebook', label: 'Facebook' },
      { value: 'snapchat', label: 'Snapchat' },
      { value: 'tiktok', label: 'TikTok' },
      { value: 'dooh', label: 'DOOH / OOH' },
      { value: 'programmatic', label: 'Programmatic' },
      { value: 'ctv', label: 'CTV / OTT' },
    ],
    defaults: ['instagram', 'youtube'],
  },
  {
    key: 'type',
    label: 'Creative type',
    options: [
      { value: 'video', label: 'Video' },
      { value: 'static', label: 'Static image' },
      { value: 'carousel', label: 'Carousel' },
      { value: 'stories', label: 'Stories / Reels' },
      { value: 'richmedia', label: 'Rich media / HTML5' },
      { value: 'dynamic', label: 'Dynamic / DCO' },
      { value: 'ugc', label: 'UGC-style' },
    ],
    defaults: ['video', 'static'],
  },
  {
    key: 'market',
    label: 'Market',
    options: [
      { value: 'uae', label: 'UAE' },
      { value: 'ksa', label: 'Saudi Arabia' },
      { value: 'bahrain', label: 'Bahrain' },
      { value: 'kuwait', label: 'Kuwait' },
      { value: 'qatar', label: 'Qatar' },
      { value: 'gcc', label: 'GCC-wide' },
      { value: 'mena', label: 'MENA-wide' },
    ],
    defaults: ['uae'],
  },
  {
    key: 'brand',
    label: 'Brand',
    options: [
      { value: 'all', label: 'All brands' },
      { value: 'bigticket', label: 'Big Ticket' },
      { value: 'uaelottery', label: 'UAE Lottery' },
      { value: 'mahzooz', label: 'Mahzooz' },
      { value: 'dubaidutyfree', label: 'Dubai Duty Free' },
      { value: 'emiratesdraw', label: 'Emirates Draw' },
    ],
    defaults: ['all'],
    exclusive: 'all',
  },
  {
    key: 'lang',
    label: 'Language',
    options: [
      { value: 'en', label: 'English' },
      { value: 'ar', label: 'Arabic' },
      { value: 'hi', label: 'Hindi' },
      { value: 'tl', label: 'Tagalog' },
    ],
    defaults: ['en', 'ar'],
  },
  {
    key: 'focus',
    label: 'Output focus',
    options: [
      { value: 'specs', label: 'Creative specs' },
      { value: 'copy', label: 'Copy / headlines' },
      { value: 'compliance', label: 'Compliance' },
      { value: 'targeting', label: 'Targeting params' },
      { value: 'trends', label: 'Live trends' },
    ],
    defaults: ['specs', 'copy'],
  },
  {
    key: 'season',
    label: 'Season / moment',
    options: [
      { value: 'evergreen', label: 'Evergreen' },
      { value: 'ramadan', label: 'Ramadan' },
      { value: 'eid', label: 'Eid' },
      { value: 'nationalday', label: 'UAE National Day' },
      { value: 'newyear', label: 'New Year' },
    ],
    defaults: ['evergreen'],
  },
]
